name: Build and Auto-Tag

on:
  push:
    branches:
      - main
  # pull_request:
  #   types:
  #     - closed  # Trigger when a PR is merged or closed

jobs:
  tag:
    if: github.event.pull_request.merged == true || github.event.pull_request.merged == null
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.tag_version.outputs.new_version }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate New Tag Version
        id: tag_version
        run: |
          LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.1.0")
          new_version=$(echo $LATEST_TAG | sed 's/^v//' | awk -F. -v OFS=. '{print $1, $2, $3+1}')
          echo "new_version=$new_version" >> $GITHUB_ENV
          echo "new_version=$new_version" >> $GITHUB_OUTPUT

      - name: Create and Push New Tag
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git tag -a "$new_version" -m "Release $new_version"
          git push origin "$new_version"

  build:
    needs: tag
    runs-on: ubuntu-latest
    env:
      new_version: ${{ needs.tag.outputs.new_version }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET 10
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Build .NET App
        run: |
          dotnet build --configuration Release /p:Version=${{ env.new_version }} /p:NuGetVersion=${{ env.new_version }}

      - name: Package Application
        run: |
          dotnet publish -c Release -o out

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-app-${{ env.new_version }}
          path: out
